version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:14.17.0'
    steps:
      - checkout
      - restore_cache:
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: npm install
      - save_cache:
          key: 'v1-dependencies-{{ checksum "package.json" }}'
          paths:
            - node_modules
      - run: npm run build
      - checkout
      - run: npm run test
      - checkout
      - run: ./node_modules/firebase-tools/lib/bin/firebase.js login:ci

# # Orchestrate our job run sequence
# workflows:
# build_and_test:
#     jobs:
#       - build
#       - test
#       - deploy